version: "3.9"

services:
  db:
    image: postgres:15
    ports:
      - "5433:5432" # Host:Container — use 5433 locally
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: ecommerce
      POSTGRES_USER: ecommerce_user
      POSTGRES_PASSWORD: ecommerce_pass
    restart: always

  web:
    build: .
    command: >
      sh -c "sleep 10 &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn backend.wsgi:application --bind 0.0.0.0:8000 --log-level debug"
    volumes:
      - .:/code
      - ./static:/code/static
      - C:\Users\gangs\ecommerce_media:/code/media
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  postgres_data:
